### ISSUE TITLE
css and js not loading

### ISSUE THREAD

**Issue by jamesragray** [vibe-d/vibed.org#69]
The site doesn't seem to be loading css and js (and looks bad). I get the following errors:
normalize.css:1          Failed to load resource: the server responded with a status of 404 ()
bootstrap.js:1             Failed to load resource: the server responded with a status of 404 ()
bootstrap.css:1          Failed to load resource: the server responded with a status of 404 ()
normalize.css:1          Failed to load resource: the server responded with a status of 404 ()
bootstrap.css:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by s-ludwig** [comment]
I've fixed this after a notification by mail earlier today. Thanks for the notice!
