### ISSUE TITLE
Pages not rendering properly

### ISSUE THREAD

**Issue by jamesragray** [vibe-d/vibed.org#70]
Many pages are not rendering properly e.g
[this page](https://vibed.org/api/vibe.data.json/Json.opIndex)

Some part of it looks like this:

```
assert(�alue["a"] == 1);assert(value["b"] == true);
```

**Comment by s-ludwig** [comment]
This was a codegen issue for newer LDC versions on Linux that I actually ran into before, but had forgotten since then. I'm compiling with DMD for now to work around it.
